blogapp/views/auth.py
from flask import Blueprint, render_template, flash, url_for, redirect, request
from flask_login import login_user, logout_user, login_required, current_user
from blogapp.forms.auth import LoginForm, RegistrationForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from blogapp import bcrypt, db, login_manager
from blogapp.models import User, Post
from blogapp.utils.auth import save_picture, send_reset_email


auth = Blueprint('auth', __name__)


@auth.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("index.landing"))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for("index.landing"))
        else:
            flash("Email and or password are incorrect. Please try again.", "danger")

    return render_template("auth/login.html", title = "Login", form = form)


@auth.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("index.landing"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pwd)
        db.session.add(user)
        db.session.commit()
        flash("You have successfully registered your account! You can now login!", "success")
        return redirect(url_for("auth.login"))

    return render_template("auth/register.html", title = "Register", form = form)


@auth.route("/logout")
def logout():
    logout_user()
    flash("You have successfully logged out!", "success")
    return redirect(url_for("index.landing"))


@auth.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account was successfully updated!", "success")
        return redirect(url_for("auth.account"))

    form.username.data = current_user.username
    form.email.data = current_user.email

    posts = current_user.posts

    return render_template("auth/account.html", title = "Account", form = form, posts = posts)


@auth.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        flash("You can't reset your password if you are already logged in", "danger")
        return redirect(url_for("posts.explore"))

    form = RequestResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with instructions to reset your password", "info")
        return redirect(url_for("auth.login"))

    return render_template('auth/reset_request.html', title = 'Reset Password', form = form)


@auth.route("/reset_password<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        flash("You can't reset your password if you are already logged in", "danger")
        return redirect(url_for("posts.explore"))
    user = User.verify_reset_token(token)

    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('auth.reset_request'))

    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pwd
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('auth.login'))

    return render_template('auth/reset_token.html', title='Reset Password', form=form)

blogapp/views/posts.py
from flask import Blueprint, render_template, flash, url_for, redirect
from flask_login import login_user, logout_user, login_required, current_user
from blogapp.forms.posts import PostForm, UpdatePostForm
from blogapp import bcrypt, db
from blogapp.models import Post, User


posts = Blueprint('posts', __name__)


@posts.route("/posts/explore")
def explore():
    posts = Post.query.order_by(Post.date_posted.desc())
    return render_template("posts/explore.html", title = "Explore", posts = posts)


@posts.route("/posts/users/<int:user_id>")
def users(user_id):
    user = User.query.get_or_404(user_id)
    posts = Post.query.filter_by(user_id = user.id)
    return render_template("posts/users.html", title = user.username, posts = posts, user = user)


@posts.route("/posts/new", methods=['GET', 'POST'])
@login_required
def new():
    form = PostForm()

    if form.validate_on_submit():
        post = Post(title = form.title.data, image_url = form.imageUrl.data, content = form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post is now up for all to see!", "success")
        return redirect(url_for("posts.explore"))

    return render_template("posts/new.html", title = "Post", form = form)


@posts.route("/posts/<int:post_id>")
def show(post_id):
    post = Post.query.get_or_404(post_id)
    post.comments.reverse()
    return render_template('posts/show.html', title = post.title, post = post)


@posts.route("/posts/<int:post_id>/edit", methods=['GET', 'POST'])
@login_required
def edit(post_id):
    form = UpdatePostForm()
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        flash("You must own that post to edit it!", "danger")
        return redirect(url_for("posts.show", post_id = post_id))

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.image_url = form.imageUrl.data
        db.session.commit()
        flash("Your post has been updated!", "success")
        return redirect(url_for("posts.show", post_id = post_id))

    form.title.data = post.title
    form.content.data = post.content
    form.imageUrl.data = post.image_url

    return render_template('posts/edit.html', title = post.title, post = post, form = form)


@posts.route("/posts/<int:post_id>/delete")
@login_required
def delete(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        flash("You must own that post to delete it!", "danger")
        return redirect(url_for("posts.show", post_id = post_id))

    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted", "success")
    return redirect(url_for("posts.explore"))

blogapp/templates/layout.html
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">

        {% if title %}
            <title>Blog App - {{ title }}</title>
        {% else %} 
            <title>Blog App</title>
        {% endif %}
    </head>
    <body>
        <div class="main-nav">
            <a class="nav-title" href="{{ url_for('index.landing') }}">Blog App</a>
            <div class="menu">
                {% if current_user.is_authenticated %}
                    <div class="nav-item">
                        <a href="{{ url_for('posts.explore') }}">Explore</a>
                    </div>
                    <div class="nav-item">
                        <a href="{{ url_for('posts.new') }}">New Post</a>
                    </div>
                    <div class="nav-item">
                        <a href="{{ url_for('auth.account') }}">Account</a>
                    </div>
                    <div class="nav-item">
                        <a href="{{ url_for('auth.logout') }}">Logout</a>
                    </div>
                {% else %}
                    <div class="nav-item">
                        <a href="{{ url_for('posts.explore') }}">Explore</a>
                    </div>
                    <div class="nav-item">
                        <a href="{{ url_for('auth.login') }}">Login</a>
                    </div>
                    <div class="nav-item">
                        <a href="{{ url_for('auth.register') }}">Register</a>
                    </div>
                {% endif %}
            </div>
        </div>
        {% with messages = get_flashed_messages(with_categories = true) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>