blogapp/forms/posts.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators = [DataRequired()])
    imageUrl = StringField('Image URL', validators = [DataRequired()])
    content = TextAreaField('Content', validators = [DataRequired()])
    submit = SubmitField('Post')


class UpdatePostForm(FlaskForm):
    title = StringField('Title', validators = [DataRequired()])
    imageUrl = StringField('Image URL', validators = [DataRequired()])
    content = TextAreaField('Content', validators = [DataRequired()])
    submit = SubmitField('Update')

blogapp/views/comments.py
from flask import Blueprint, render_template, flash, url_for, redirect, request
from flask_login import login_required, current_user
from blogapp import login_manager
from blogapp.models import Post, Comment
from blogapp.forms.comments import CommentForm, UpdateCommentForm
from blogapp import db


comments = Blueprint('comments', __name__)


@comments.route("/posts/<int:post_id>/comments/new", methods=['GET', 'POST'])
@login_required
def new(post_id):
    form = CommentForm()
    post = Post.query.get_or_404(post_id)

    if form.validate_on_submit():
        comment = Comment(content=form.content.data, author=current_user, post=post)
        db.session.add(comment)
        db.session.commit()
        flash("Your comment is now up for all to see!", "success")
        return redirect(url_for('posts.show', post_id=post.id))


    post = Post.query.get_or_404(post_id)
    return render_template("comments/new.html", title = "New Comment", form = form, post = post)


@comments.route("/posts/<int:post_id>/comments/<int:comment_id>/edit", methods=['GET', 'POST'])
@login_required
def edit(post_id, comment_id):
    form = UpdateCommentForm()
    comment = Comment.query.get_or_404(comment_id)
    post = Post.query.get_or_404(post_id)

    if comment.author != current_user:
        flash("You must own the comment to edit it!", "danger")
        return redirect("posts.show", post_id=post_id)

    if form.validate_on_submit():
        comment.content = form.content.data
        db.session.commit()
        flash("Your comment has been updated!", "success")
        return redirect(url_for('posts.show', post_id=post.id))

    form.content.data = comment.content

    return render_template("comments/edit.html", title = "New Comment", form = form, post = post, comment = comment)


@comments.route("/posts/<int:post_id>/comments/<int:comment_id>/delete")
@login_required
def delete(post_id, comment_id):
    post = Post.query.get_or_404(post_id)
    comment = Comment.query.get_or_404(comment_id)

    if comment.author != current_user:
        flash("You must own the comment to edit it!", "danger")
        return redirect("posts.show", post_id=post_id)

    db.session.delete(comment)
    db.session.commit()

    flash("Your comment has been deleted", "success")
    return redirect(url_for("posts.show", post_id=post_id))

blogapp/views/posts.py
from flask import Blueprint, render_template, flash, url_for, redirect
from flask_login import login_user, logout_user, login_required, current_user
from blogapp.forms.posts import PostForm, UpdatePostForm
from blogapp import bcrypt, db
from blogapp.models import Post, User


posts = Blueprint('posts', __name__)


@posts.route("/posts/explore")
def explore():
    posts = Post.query.order_by(Post.date_posted.desc())
    return render_template("posts/explore.html", title = "Explore", posts = posts)


@posts.route("/posts/users/<int:user_id>")
def users(user_id):
    user = User.query.get_or_404(user_id)
    posts = Post.query.filter_by(user_id = user.id)
    return render_template("posts/users.html", title = user.username, posts = posts, user = user)


@posts.route("/posts/new", methods=['GET', 'POST'])
@login_required
def new():
    form = PostForm()

    if form.validate_on_submit():
        post = Post(title = form.title.data, image_url = form.imageUrl.data, content = form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post is now up for all to see!", "success")
        return redirect(url_for("posts.explore"))

    return render_template("posts/new.html", title = "Post", form = form)


@posts.route("/posts/<int:post_id>")
def show(post_id):
    post = Post.query.get_or_404(post_id)
    post.comments.reverse()
    return render_template('posts/show.html', title = post.title, post = post)


@posts.route("/posts/<int:post_id>/edit", methods=['GET', 'POST'])
@login_required
def edit(post_id):
    form = UpdatePostForm()
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        flash("You must own that post to edit it!", "danger")
        return redirect(url_for("posts.show", post_id = post_id))

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.image_url = form.imageUrl.data
        db.session.commit()
        flash("Your post has been updated!", "success")
        return redirect(url_for("posts.show", post_id = post_id))

    form.title.data = post.title
    form.content.data = post.content
    form.imageUrl.data = post.image_url

    return render_template('posts/edit.html', title = post.title, post = post, form = form)


@posts.route("/posts/<int:post_id>/delete")
@login_required
def delete(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        flash("You must own that post to delete it!", "danger")
        return redirect(url_for("posts.show", post_id = post_id))

    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted", "success")
    return redirect(url_for("posts.explore"))

blogapp/templates/posts/edit.html
{% extends 'layout.html' %}
{% block content %}
    <form action="" method="POST" class="main-form">
        {{ form.hidden_tag() }}
        <h1 class="form-title">Update Post</h1>
        <div class="form-group">
            {{ form.title.label }}
            {% if form.title.errors %}
                {{ form.title(class = "form-input invalid-input") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.title(class = "form-input") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.imageUrl.label }}
            {% if form.imageUrl.errors %}
                {{ form.imageUrl(class = "form-input invalid-input") }}
                <div class="invalid-feedback">
                    {% for error in form.imageUrl.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.imageUrl(class = "form-input") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.content.label }}
            {% if form.content.errors %}
                {{ form.content(class = "form-text-area invalid-input") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.content(class = "form-text-area") }}
            {% endif %}
        </div>
        {{ form.submit(class = "form-submit") }}
    </form>
{% endblock content %}

blogapp/templates/posts/explore.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="text-center">Explore Posts</h1>
    {% for post in posts %}
        <div class="post-container">
            <img class="post-thumbnail-img" src="{{ post.image_url }}">
            <div class="post-thumbnail-content">
                <h1 class="post-thumbnail-title">{{ post.title }}</h1>
                <p>{{ post.content[0:180] }}...</p>
                <p>By: {{ post.author.username }}</p>
                <a class="post-thumbnail-read-more" href="{{ url_for('posts.show', post_id = post.id) }}">Read More</a>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

blogapp/templates/posts/new.html
{% extends 'layout.html' %}
{% block content %}
    <form action="" method="POST" class="main-form">
        {{ form.hidden_tag() }}
        <h1 class="form-title">New Post</h1>
        <div class="form-group">
            {{ form.title.label }}
            {% if form.title.errors %}
                {{ form.title(class = "form-input invalid-input") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.title(class = "form-input") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.imageUrl.label }}
            {% if form.imageUrl.errors %}
                {{ form.imageUrl(class = "form-input invalid-input") }}
                <div class="invalid-feedback">
                    {% for error in form.imageUrl.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.imageUrl(class = "form-input") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.content.label }}
            {% if form.content.errors %}
                {{ form.content(class = "form-text-area invalid-input") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.content(class = "form-text-area") }}
            {% endif %}
        </div>
        {{ form.submit(class = "form-submit") }}
    </form>
{% endblock content %}

blogapp/templates/posts/show.html
{% extends 'layout.html' %}
{% block content %}
    <div class="show-post-container">
        <img class="show-post-img" src="{{ post.image_url }}">
        <div class="show-post-content">
            <h1>{{ post.title }}</h1>
            <p>{{ post.content }}</p>
            <p><strong>By: {{ post.author.username }}</strong></p>
            <p><strong>Posted On: {{ post.date_posted.strftime('%m-%d-%Y') }}</strong></p>
            {% if current_user != post.author %}
                <a class="show-post-btn bg-purple" href="{{ url_for('posts.users', user_id = post.author.id) }}">View Account</a>
            {% endif %}
            {% if current_user.id %}
                <a class="show-post-btn bg-baby-blue" href="{{ url_for('comments.new', post_id = post.id) }}">Comment</a>
                {% if post.author == current_user %}
                    <a class="show-post-btn bg-info" href="{{ url_for('posts.edit', post_id = post.id) }}">Edit</a>
                    <a class="show-post-btn bg-danger" href="{{ url_for('posts.delete', post_id = post.id) }}">Delete</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    {% if post.comments %}
        <div class="main-comments-container">
            <div class="padded">
                <h1>Comments</h1>
                {% for comment in post.comments %}
                    <div class="comment-container">
                        <p>- {{ comment.author.username }}</p>
                        <h4>{{ comment.content }}</h4>
                        {% if current_user and comment.author == current_user %}
                            <a class="show-post-btn-small bg-info" href="{{ url_for('comments.edit', comment_id = comment.id, post_id = post.id) }}">Edit</a>
                            <a class="show-post-btn-small bg-danger" href="{{ url_for('comments.delete', comment_id = comment.id, post_id = post.id) }}">Delete</a>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock content %}

blogapp/templates/posts/users.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="text-center">{{ user.username }} Post's</h1>
    {% for post in posts %}
        <div class="post-container">
            <img class="post-thumbnail-img" src="{{ post.image_url }}">
            <div class="post-thumbnail-content">
                <h1 class="post-thumbnail-title">{{ post.title }}</h1>
                <p>{{ post.content[0:180] }}...</p>
                <p>By: {{ post.author.username }}</p>
                <a class="post-thumbnail-read-more" href="{{ url_for('posts.show', post_id = post.id) }}">Read More</a>
            </div>
        </div>
    {% endfor %}
{% endblock content %}